apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nagp

spec:
  accessModes:
    - ReadWriteOnce
storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi